name: Prometheus Setup

on:
  push:
    paths:
      - 'monitoring/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  setup-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Prometheus & Start Monitoring
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz
          tar xvfz prometheus-*.tar.gz
          cd prometheus-*
          ./prometheus --config.file=prometheus.yml &
